import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/ui/navBar";
import Image from "next/image";
import StarknetProvider from "@/components/providers/starknet-provider";
import { NotificationProvider } from "@/components/providers/notification-provider";

export const metadata: Metadata = {
  title: "Starkpay Africa",
  description: "Generated by Starkpay Africa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StarknetProvider>
          <NotificationProvider>
            <NavBar />
            <div>{children}</div>
          </NotificationProvider>
        </StarknetProvider>
      </body>
    </html>
  );
}
