import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/ui/navBar";
import StarknetProvider from "@/components/providers/starknet-provider";
import { NotificationProvider } from "@/components/providers/notification-provider";
// import { ThemeProvider } from "@/context/ThemeContext";

export const metadata: Metadata = {
  title: "Starkpay Africa",
  description: "Generated by Starkpay Africa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StarknetProvider>
          {/* <ThemeProvider> */}
            <NotificationProvider>
              <NavBar />
              <div>{children}</div>
            </NotificationProvider>
          {/* </ThemeProvider> */}
        </StarknetProvider>
      </body>
    </html>
  );
}
