import type { Metadata } from "next";
import "../globals.css";
import StarknetProvider from "@/components/providers/starknet-provider";



export const metadata: Metadata = {
  title: "Swift",
  description: "Generated by Swift",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

          <div>{children}</div>


  );
}
