import type { Metadata } from "next";
import "../globals.css";
import StarknetProvider from "@/components/providers/starknet-provider";



export const metadata: Metadata = {
  title: "Starkpay Africa",
  description: "Generated by Starkpay Africa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        
      >
        <StarknetProvider>
          {/* <SideNav /> */}
          <div>{children}</div>
        </StarknetProvider>
      </body>
    </html>
  );
}
